const LOGIN = 'login';
const Product = '/Products/GetAllProducts';
const REGISTER = 'register';
const CategoryProducts = '/Products/GetProductByCategoryId';
const Category = '/Category/GetAllProducts';
const addtofavoret = '/Favorite/Add';
const productsdetails = '/Products/FindById';
const findfavbyuserid='/Favorite/FindFavoriteByUserId';
const DeleteFromFavByProductId='/Favorite/DeleteByProductId';
